#
# tst pipeline with k8s integration
#


stages:
  - test

variables:
  NS: build-$CI_PIPELINE_ID

k1:
  stage: test
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  tags:
    - kubernetes

  script:
    - kubectl create namespace $NS
    - kubectl -n $NS get pods
    - sleep 120

  environment:
    testing
