#
# tst pipeline with k8s integration
#


stages:
  - test

variables:
  #NS: build-$CI_PIPELINE_ID
  NS: testing 

k1:
  stage: test
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  tags:
    - kubernetes

  script:
    #- kubectl create namespace $NS
    - kubectl config set-context --current --namespace=$NS
    - kubectl get pods
    - kubectl run wn-$CI_PIPELINE_ID --image=centos:8  --restart=Never  --command -- sleep 120
#    - kubectl delete pod wn-$CI_PIPELINE_ID 

  environment:
    testing
