#
# tst pipeline with k8s integration
#


stages:
  - test

variables:
  #NS: build-$CI_PIPELINE_ID
  NS: testing

k1:
  stage: test
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  tags:
    - kubernetes

  script:
    #- kubectl create namespace $NS
    - kubectl config set-context --current --namespace=$NS
    - kubectl apply -f deployments/postgresql-service.yml
    - kubectl apply -f deployments/zookeeper.yml
    - kubectl apply -f deployments/dcache-service.yml
    - kubectl run wn-$CI_PIPELINE_ID --image=dcache/pynfs:0.1 --restart=Never  --command -- sleep 3600
    - sleep 20
    - kubectl exec wn-$CI_PIPELINE_ID  -- /bin/bash -c "cd /pynfs/nfs4.0; python3 -u ./testserver.py --xml=/xunit-report-v40.xml --maketree dcache-svc:/data all; exit 0"
    - kubectl cp  wn-$CI_PIPELINE_ID:/xunit-report-v40.xml xunit-report-v40.xml
    - kubectl delete pod wn-$CI_PIPELINE_ID

  environment:
    testing

  artifacts:
    reports:
      junit:
        - "xunit*.xml"

