#
# tst pipeline with k8s integration
#


stages:
  - test

variables:
  #NS: build-$CI_PIPELINE_ID
  NS: testing 

k1:
  stage: test
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  tags:
    - kubernetes

  script:
    #- kubectl create namespace $NS
    - kubectl config set-context --current --namespace=$NS
    - kubectl apply -f deployments/postgresql-service.yml
    - kubectl apply -f deployments/zookeeper.yml
    - kubectl apply -f deployments/dcache-service.yml
    - kubectl get pods

  environment:
    testing
