#
# test pipeline with k8s integration
#


stages:
  - prepare
  - test_deploy
  - testing
  - collect
  - cleanup

variables:
  NS: build-$CI_PIPELINE_ID
  CHECK_TIMEOUT: --timeout=180s
  RANCHER_CLI_VERSION: v2.4.14
  AUTOCA_URL: https://ci.dcache.org:8083/


#
# prepare kubernetes env for the build
#
prepare_env:
  stage: prepare
  image:
    name: rancher/cli2
    entrypoint: ["/bin/cat"]
  script:
    - rancher login --token $RANCHER_TOKEN $RANCHER_ENDPOINT
    - rancher namespace create $NS


deploy:
  stage: test_deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  tags:
    - kubernetes
  script:
    - kubectl config set-context --current --namespace=$NS

    - kubectl apply -f deployments/postgresql-service.yml
    - sleep 10
    - kubectl wait $CHECK_TIMEOUT --for=condition=ready pod -l app=postgresql

    - kubectl apply -f deployments/zookeeper.yml
    - sleep 10
    - kubectl wait $CHECK_TIMEOUT --for=condition=ready pod -l app=zk

    - kubectl apply -f deployments/dcache-service.yml
    - sleep 10
    - kubectl wait $CHECK_TIMEOUT --for=condition=Ready pod -l app=dcache

  environment:
    testing


cvmfs_test:
  stage: test_deploy
  image: centos:7
  tags:
    - cvmfs
  script:
    - yum install -y curl python openssl
    - rpm -i https://www.desy.de/~tigran/ca_dCacheORG-3.0-4.noarch.rpm
    - curl https://raw.githubusercontent.com/kofemann/autoca/v1.0-py2/pyclient/autoca-client -o autoca-client
    - chmod a+x autoca-client
    - ./autoca-client -n -k userkey.pem -c usercert.pem ${AUTOCA_URL} "Kermit the frog"
    - ls /cvmfs/grid.desy.de
    - cp /cvmfs/grid.desy.de/etc/profile.d/grid-ui-env-old.sh /tmp/grid-ui-env.sh
    - sed -i -e '12,17d' /tmp/grid-ui-env.sh
    - set -o allexport
    - . /tmp/grid-ui-env.sh
    - env 
    - arcproxy --version


pynfs_tests:
  stage: testing
  allow_failure: true
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  tags:
    - kubernetes
  script:
    - kubectl config set-context --current --namespace=$NS

    - kubectl run pynfs-tester --image=dcache/pynfs:0.1 --restart=Never  --command -- sleep 3600
    - kubectl wait $CHECK_TIMEOUT --for=condition=Ready pods --all

    - kubectl exec pynfs-tester -- /bin/bash -c "cd /pynfs/nfs4.0; python3 -u ./testserver.py --xml=/xunit-report-v40.xml --maketree dcache-svc:/data all; exit 0"
    - kubectl exec pynfs-tester -- /bin/bash -c "cd /pynfs/nfs4.1; python3 -u ./testserver.py --xml=/xunit-report-v41.xml --maketree dcache-svc:/data all; exit 0"

    - kubectl cp pynfs-tester:/xunit-report-v40.xml xunit-report-v40.xml
    - kubectl cp pynfs-tester:/xunit-report-v41.xml xunit-report-v41.xml
  environment:
    testing

  artifacts:
    reports:
      junit:
        - "xunit*.xml"

xrdcp_tests:
  stage: testing
  allow_failure: true
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  tags:
    - kubernetes
  script:
    - kubectl config set-context --current --namespace=$NS

    - kubectl run xrdcp-tester --image=centos:7 --restart=Never  --command -- sleep 3600
    - kubectl wait $CHECK_TIMEOUT --for=condition=Ready pods --all

    - kubectl exec xrdcp-tester -- yum install -y epel-release
    - kubectl exec xrdcp-tester -- yum install -y xrootd-client
    - kubectl exec xrdcp-tester -- xrdcp /etc/hosts root://dcache-svc/tests/file.data
    - kubectl exec xrdcp-tester -- xrdcp root://dcache-svc/tests/file.data /tmp/file.data
    - kubectl exec xrdcp-tester -- cmp /etc/hosts /tmp/file.data
  environment:
    testing



collect_logs:
  stage: collect
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  tags:
    - kubernetes
  script:
    - kubectl config set-context --current --namespace=$NS
    - kubectl logs -l app=dcache --all-containers --tail=-1 > dcache.log
    - kubectl logs -l app=postgresql --all-containers --tail=-1 > postgres.log
    - kubectl logs -l app=zk --all-containers --tail=-1 > zk.log
  environment:
    testing
  artifacts:
    paths:
    - "*.log"


#
# dispose kubernetes respurces
#
cleanup:
  stage: cleanup
  image:
    name: rancher/cli2
    entrypoint: ["/bin/cat"]
  script:
    - rancher login --token $RANCHER_TOKEN $RANCHER_ENDPOINT
    - rancher namespace delete $NS


