#
# tst pipeline with k8s integration
#


stages:
  - test

variables:
  NS: build-$CI_PIPELINE_ID
  CHECK_TIMEOUT: --timeout=180s
  RANCHER_CLI_VERSION: v2.4.14

k1:
  stage: test
  image:
    name: centos:8
    entrypoint: [""]
  tags:
    - kubernetes

  before_script:
    - dnf install -y curl
    - curl -LO https://releases.rancher.com/cli2/$RANCHER_CLI_VERSION/rancher-linux-amd64-$RANCHER_CLI_VERSION.tar.gz
    - tar zxvf rancher-linux-amd64-$RANCHER_CLI_VERSION.tar.gz
    - mv rancher-$RANCHER_CLI_VERSION/rancher /usr/local/bin/
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - mv kubectl /usr/local/bin
    - chmod +x /usr/local/bin/kubectl /usr/local/bin/rancher

    - rancher login --token $RANCHER_TOKEN $RANCHER_ENDPOINT
    - rancher namespace create $NS

  script:
    - kubectl config set-context --current --namespace=$NS

    - kubectl apply -f deployments/postgresql-service.yml
    - kubectl apply -f deployments/zookeeper.yml
    - kubectl apply -f deployments/dcache-service.yml
    #- kubectl wait $CHECK_TIMEOUT --for=condition=Ready --all StatefulSets 
    - sleep 180

    - kubectl run wn-$CI_PIPELINE_ID --image=dcache/pynfs:0.1 --restart=Never  --command -- sleep 3600
    - kubectl wait $CHECK_TIMEOUT --for=condition=Ready pods --all

    - kubectl exec wn-$CI_PIPELINE_ID -- /bin/bash -c "cd /pynfs/nfs4.0; python3 -u ./testserver.py --xml=/xunit-report-v40.xml --maketree dcache-svc:/data all; exit 0"
    - kubectl exec wn-$CI_PIPELINE_ID -- /bin/bash -c "cd /pynfs/nfs4.1; python3 -u ./testserver.py --xml=/xunit-report-v41.xml --maketree dcache-svc:/data all; exit 0"

    - kubectl cp wn-$CI_PIPELINE_ID:/xunit-report-v40.xml xunit-report-v40.xml
    - kubectl cp wn-$CI_PIPELINE_ID:/xunit-report-v41.xml xunit-report-v41.xml

  after_script:
    # try to clean at the end
    - kubectl config set-context --current --namespace=$NS
    - kubectl delete -f deployments/dcache-service.yml
    - kubectl delete -f deployments/zookeeper.yml
    - kubectl delete -f deployments/postgresql-service.yml
    - rancher namespace delete $NS

  environment:
    testing

  artifacts:
    reports:
      junit:
        - "xunit*.xml"

