#
# tst pipeline with k8s integration
#


stages:
  - test

variables:
  NS: build-$CI_PIPELINE_ID

k1:
  stage: test
  image:
    name: rancher/kubectl:v1.22.2
    entrypoint: ["/usr/bin/env"]
  tags:
    - kubernetes

  script:
    - kubectl create namespace $NS

  environment:
    testing
